name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  id-token: write
  actions: read
  issues: write
  checks: write
  security-events: write


jobs:
  sast:
    name: SAST Scan with Snyk Code
    runs-on: ubuntu-latest
    # needs: lint-test
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
          
      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk CLI
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Code SAST Scan
        run: snyk code test --severity-threshold=high --json-file-output=snyk-code-report.json || true

      - name: Install snyk-to-html
        run: npm install -g snyk-to-html
      
      - name: Convert Snyk JSON to HTML
        run: snyk-to-html -i snyk-code-report.json -o snyk-code-report.html
      
      - name: Upload Snyk Code Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-code-report
          path: snyk-code-report.html
        if: always()

      - name: Upload Snyk Code Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-code-report
          path: snyk-code-report.json
        if: always()
